import { Theme } from '../interfaces/theme';

const darkTheme: Theme = {
  primary: '#F9B233',
  primaryDark: '#DF9000',
  primaryLight: '#FFF8DE',
  primaryOpacity: 'rgba(249, 178, 51, 0.4)',
  secondary: '#F7F8F9',
  secondaryLight: '#FFF3CF',
  secondaryDark: '#E8E7EE',
  lighthen: '#000000',
  lighthen1: '#53555C',
  lighthen2: '#787C87',
  lighthen3: '#B1B4C4',
  darken1: '#C6C9D8',
  darken2: '#E8EAF3',
  darken3: '#F5F7FB',
  darken: '#FFFFFF',
  danger: '#FF5F5F',
  dangerLight: '#FBB6B4',
  dangerSuperLight: '#FEF2F1',
  success: '#287D3C',
  successLight: '#EDF9F0',
  successSuperLight: '#F9FCFA',
  successSecondary: '#5ACA75',
  warningLight: '#FBEBC8',
  info: '#2e5aac',
  infoLight: '#EEF2FA',
  containerBg: '#000000',
  containerSecondaryBg: '#202124',
  dividerColor: '#3E4043',
  card: {
    color: '#F7F8F9',
  },
  input: {
    bg: '#FFFFFF33',
    borderRadius: '6px',
    borderColor: '#A7A9BC',
  },
  statusBarColor: '#FFFFFF',
  text: {
    black: 'Montserrat-Black',
    blackItalic: 'Montserrat-BlackItalic',
    extrabold: 'Montserrat-ExtraBold',
    extraboldItalic: 'Montserrat-ExtraBoldItalic',
    bold: 'Montserrat-Bold',
    boldItalic: 'Montserrat-BoldItalic',
    semibold: 'Montserrat-SemiBold',
    semiboldItalic: 'Montserrat-SemiBoldItalic',
    medium: 'Montserrat-Medium',
    mediumItalic: 'Montserrat-MediumItalic',
    regular: 'Montserrat-Regular',
    regularItalic: 'Montserrat-RegularItalic',
    light: 'Montserrat-Light',
    lightItalic: 'Montserrat-LightItalic',
    extralight: 'Montserrat-ExtraLight',
    extralightItalic: 'Montserrat-ExtraLightItalic',
    thin: 'Montserrat-Thin',
    thinItalic: 'Montserrat-ThinItalic',
  },
};

export default darkTheme;
